---
- hosts: all
  become: yes
  tasks:
  - name: install jdk
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - openjdk-8-jdk-headless
      - openjdk-8-jre-headless
      - apache2

  - name: add key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: add repo
    apt_repository:
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      state: present
      filename: /etc/apt/sources.list.d/jenkins.list

  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: restart jenkins
    service:
      name: jenkins
      state: started

  - name: get intial password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: find_output
    
  - debug: 
      var: find_output.stdout

